"""日記とコメントの表を作る

Revision ID: 23bc4255c9c5
Revises: 
Create Date: 2026-10-01 14:09:40.460205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bc4255c9c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False, comment='書いた人。Cognito のユーザーの sub'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='書いた時刻'),
    sa.Column('migration_id', sa.BigInteger(), nullable=True, comment='CSV から取り込んだ行の、取り込む前の id。コメントの CSV の diary_id はこれで日記を引く'),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diary_user_id_time', 'diary', ['user_id', 'time'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False, comment='書いた人。Cognito のユーザーの sub'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='書いた時刻'),
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.BigInteger(), nullable=True, comment='CSV から取り込んだ行の、取り込む前の id。コメントの CSV の diary_id はこれで日記を引く'),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_diary_id', 'comment', ['diary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_diary_id', table_name='comment')
    op.drop_table('comment')
    op.drop_index('ix_diary_user_id_time', table_name='diary')
    op.drop_table('diary')
    # ### end Alembic commands ###
