"""未来へ送った日記の書いた時刻を足す

Revision ID: 3addc44f7cdf
Revises: 23bc4255c9c5
Create Date: 2026-10-01 22:49:39.686207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3addc44f7cdf'
down_revision: Union[str, Sequence[str], None] = '23bc4255c9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('written_at', sa.DateTime(timezone=True), nullable=True, comment='未来へ送った日記の、書いた時刻。time は届く時刻。ふだんの日記は NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'written_at')
    # ### end Alembic commands ###
