/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Diaries
         * @description 日本時間の `start_date` から `end_date` まで(両端を含む)の日記を、コメント付きで時刻の順に返す。
         */
        get: operations["list_diaries_api_diaries_get"];
        put?: never;
        /** Commit Diary */
        post: operations["commit_diary_api_diaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diaries/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Similar Diaries
         * @description `text` に似た日記の数と、似ている順の頭の何件か。
         */
        post: operations["search_similar_diaries_api_diaries_similar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/on-this-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List On This Day
         * @description `day` と同じ月日の前後 `around_days` 日の日記を、年ごとに新しい年から。
         */
        get: operations["list_on_this_day_api_on_this_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diary-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count Diaries By Day
         * @description 日本時間の暦の日ごとの、日記の件数と文字数。書いた日だけ。
         */
        get: operations["count_diaries_by_day_api_diary_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/future-diaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Future Diaries
         * @description まだ届いていない未来の日記の、届く時刻と書いた時刻。本文は返さない。
         */
        get: operations["list_future_diaries_api_future_diaries_get"];
        put?: never;
        /** Send Future Diary */
        post: operations["send_future_diary_api_future_diaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diaries/{diary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Diary */
        get: operations["read_diary_api_diaries__diary_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Diary
         * @description 日記を、付いたコメントごと消す。
         */
        delete: operations["delete_diary_api_diaries__diary_id__delete"];
        options?: never;
        head?: never;
        /** Update Diary */
        patch: operations["update_diary_api_diaries__diary_id__patch"];
        trace?: never;
    };
    "/api/diaries/{diary_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments */
        get: operations["list_comments_api_diaries__diary_id__comments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Comment */
        get: operations["read_comment_api_comments__comment_id__get"];
        put?: never;
        post?: never;
        /** Delete Comment */
        delete: operations["delete_comment_api_comments__comment_id__delete"];
        options?: never;
        head?: never;
        /** Update Comment */
        patch: operations["update_comment_api_comments__comment_id__patch"];
        trace?: never;
    };
    "/api/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Comment */
        post: operations["commit_comment_api_comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csv/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Csv
         * @description 取り込み直せる形の CSV を返す。
         */
        get: operations["export_csv_api_csv__kind__get"];
        put?: never;
        /**
         * Import Csv
         * @description CSV を取り込む。コメントは、先に取り込んだ日記の CSV の id を `diary_id` で指す。
         */
        post: operations["import_csv_api_csv__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legacy-db/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize Legacy Db
         * @description 以前の SQLite の db ファイル(本文にそのまま)に、誰の日記が何件あるか。db には触れない。
         */
        post: operations["summarize_legacy_db_api_legacy_db_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legacy-db/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Legacy Db
         * @description 以前の SQLite の db ファイル(本文にそのまま)から、`source_user_id` の日記とコメントを取り込む。
         */
        post: operations["import_legacy_db_api_legacy_db_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CommentCreateForm */
        CommentCreateForm: {
            /** Diary Id */
            diary_id: number;
            /** Text */
            text: string;
            /** Time */
            time?: string | null;
        };
        /** CommentRecord */
        CommentRecord: {
            /** Id */
            id: number;
            /** Diary Id */
            diary_id: number;
            /** Time */
            time: string;
            /** Text */
            text: string;
        };
        /** CommentUpdateForm */
        CommentUpdateForm: {
            /** Text */
            text: string;
        };
        /** CsvImportRequest */
        CsvImportRequest: {
            /** Text */
            text: string;
        };
        /**
         * DayCount
         * @description 日本時間の暦の日ごとの、日記の件数と文字数。
         */
        DayCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Diaries */
            diaries: number;
            /** Chars */
            chars: number;
        };
        /** DeletedComment */
        DeletedComment: {
            /** Id */
            id: number;
            /** Diary Id */
            diary_id: number;
        };
        /** DeletedDiary */
        DeletedDiary: {
            /** Id */
            id: number;
            /** Comments */
            comments: number;
        };
        /** DiaryCreateForm */
        DiaryCreateForm: {
            /** Text */
            text: string;
            /** Time */
            time?: string | null;
        };
        /** DiaryRecord */
        DiaryRecord: {
            /** Id */
            id: number;
            /** Time */
            time: string;
            /** Written At */
            written_at: string | null;
            /** Text */
            text: string;
            /** Comments */
            comments: components["schemas"]["CommentRecord"][];
        };
        /** DiaryUpdateForm */
        DiaryUpdateForm: {
            /** Text */
            text: string;
        };
        /** FutureDiaryCreateForm */
        FutureDiaryCreateForm: {
            /** Text */
            text: string;
            /**
             * Deliver On
             * Format: date
             */
            deliver_on: string;
        };
        /**
         * FutureDiaryRecord
         * @description 封をした未来の日記。届くまで本文は返さない。
         */
        FutureDiaryRecord: {
            /** Id */
            id: number;
            /** Time */
            time: string;
            /** Written At */
            written_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Dialect */
            dialect: string;
        };
        /** Imported */
        Imported: {
            /** Added */
            added: number;
            /** Skipped */
            skipped: number;
        };
        /** LegacyDbSummary */
        LegacyDbSummary: {
            /** Users */
            users: components["schemas"]["LegacyUser"][];
            /** Unlinked Comments */
            unlinked_comments: number;
        };
        /** LegacyImported */
        LegacyImported: {
            diaries: components["schemas"]["Imported"];
            comments: components["schemas"]["Imported"];
        };
        /**
         * LegacyUser
         * @description 以前の db に日記を持つ人一人ぶん。`user_id` は以前の Cognito のユーザーの sub。
         */
        LegacyUser: {
            /** User Id */
            user_id: string;
            /** Diaries */
            diaries: number;
            /** Comments */
            comments: number;
            /** First Time */
            first_time: string;
            /** Last Time */
            last_time: string;
        };
        /**
         * OnThisDayYear
         * @description ある年の、同じ月日の前後の日記。
         */
        OnThisDayYear: {
            /** Year */
            year: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Diaries */
            diaries: components["schemas"]["DiaryRecord"][];
        };
        /** SimilarDiaries */
        SimilarDiaries: {
            /** Total */
            total: number;
            /** Diaries */
            diaries: components["schemas"]["SimilarDiary"][];
        };
        /** SimilarDiary */
        SimilarDiary: {
            /** Score */
            score: number;
            diary: components["schemas"]["DiaryRecord"];
        };
        /** SimilarSearchRequest */
        SimilarSearchRequest: {
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_api_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_diaries_api_diaries_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_diary_api_diaries_post: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiaryCreateForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_similar_diaries_api_diaries_similar_post: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarDiaries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_on_this_day_api_on_this_day_get: {
        parameters: {
            query: {
                day: string;
                around_days?: number;
            };
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnThisDayYear"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_diaries_by_day_api_diary_counts_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayCount"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_future_diaries_api_future_diaries_get: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FutureDiaryRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_future_diary_api_future_diaries_post: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FutureDiaryCreateForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FutureDiaryRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_diary_api_diaries__diary_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                diary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_diary_api_diaries__diary_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                diary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedDiary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_diary_api_diaries__diary_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                diary_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiaryUpdateForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comments_api_diaries__diary_id__comments_get: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                diary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_comment_api_comments__comment_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_comment_api_comments__comment_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedComment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_comment_api_comments__comment_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdateForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_comment_api_comments_post: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_csv__kind__get: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                kind: "diary" | "comment";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_csv_api_csv__kind__post: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path: {
                kind: "diary" | "comment";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CsvImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Imported"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_legacy_db_api_legacy_db_summary_post: {
        parameters: {
            query?: never;
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyDbSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_legacy_db_api_legacy_db_import_post: {
        parameters: {
            query: {
                source_user_id: string;
            };
            header?: {
                "x-diary-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyImported"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
